<?php

namespace AppBundle\Repository;

/**
 * PlayerGameScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerGameScoreRepository extends \Doctrine\ORM\EntityRepository
{
}
