<?php

namespace AppBundle\Repository;

/**
 * PlayerScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerScoreRepository extends \Doctrine\ORM\EntityRepository
{
}
